### ISSUE TITLE
Multiple playback windows

### ISSUE THREAD

**Issue by jpginc** [jpginc/csse3002-java#2]
When you click open twice quickly it opens the playback mode twice. @t-ho

**Comment by t-ho** [comment]
Yeah, I know! Actually, it's not a bug! The launch mode disappears immediately after clicking Open button, while the loading time of pattern in view mode too long, so I just temporarily change the order of the setVisible functions. When we implement real Open function, I'm going to put it back!

**Comment by t-ho** [comment]
Fixed!
